<a href="https://colab.research.google.com/github/truongtommy/nyu-python-public-policy/blob/master/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd 
from google.colab import drive

In [0]:
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
#Reading in 311 data set from My Drive 
df = pd.read_csv('/content/drive/My Drive/Data for Python/cleaned_311_data.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (9,18,21,32,35) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [0]:
#Using min function to search date created
df.created_date.min()

'01/01/2019 01:00:00 PM'

In [0]:
#Using max function to search date created 
df.created_date.max()

'12/31/2018 12:59:41 PM'

In [0]:
df.head()

   Unnamed: 0  unique_key  ...  longitude                                 location
0           0    39888071  ... -73.942942   (40.79333937834769, -73.9429417746998)
1           1    39889166  ... -73.953071   (40.82012422332215, -73.9530712339799)
2           2    39882869  ... -73.951399   (40.67080917938279, -73.9513990916184)
3           3    39894246  ... -73.990517  (40.74026158873342, -73.99051651686905)
4           4    39881329  ... -73.750990  (40.68814402968042, -73.75098958473612)

[5 rows x 42 columns]

In [0]:
df.tail()

         Unnamed: 0  ...                                 location
2859006     2859195  ...   (40.87970084316435, -73.9010571445122)
2859007     2859196  ...  (40.70178323733244, -73.92055493919345)
2859008     2859197  ...   (40.66999185896368, -73.9224889475533)
2859009     2859198  ...                                      NaN
2859010     2859199  ...  (40.63679359185655, -74.15397942810047)

[5 rows x 42 columns]

In [0]:
df.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2859011 entries, 0 to 2859010
Data columns (total 42 columns):
Unnamed: 0                        int64
unique_key                        int64
created_date                      object
closed_date                       object
agency                            object
agency_name                       object
complaint_type                    object
descriptor                        object
location_type                     object
incident_zip                      object
incident_address                  object
street_name                       object
cross_street_1                    object
cross_street_2                    object
intersection_street_1             object
intersection_street_2             object
address_type                      object
city                              object
landmark                          object
facility_type                     object
status                            object
due_date                          object
resolution_description            object
resolution_action_updated_date    object
community_board                   object
bbl                               float64
borough                           object
x_coordinate_(state_plane)        float64
y_coordinate_(state_plane)        float64
open_data_channel_type            object
park_facility_name                object
park_borough                      object
vehicle_type                      object
taxi_company_borough              object
taxi_pick_up_location             object
bridge_highway_name               object
bridge_highway_direction          object
road_ramp                         object
bridge_highway_segment            object
latitude                          float64
longitude                         float64
location                          object
dtypes: float64(5), int64(2), object(35)
memory usage: 916.1+ MB

3. The min and max functions give you the minimum and maximum dates according to where the date lies within the year. For example, the min function gave the first day of the year of 2019 and the max function gave the last day of the year of 2018. The min and the max functions are most likley not used for dates as they are not usually numeric elements in a dataset. Some times dates are even read as strings. The head and tail functions give you the actual first and last entries by date created.

Tutorial Questions: 

1. In the code above, I used df.info to find the type of each variable in the dataset. What is the difference between object, float64, and int64?
2. When using the "group.by" function, can you combine rows into a new group?